export const items = {
  leadership: [
    {
      id: 1,
      subject: "퍼포먼스 리더십",
      summ: "성과창출로 직결되는 실천주의적 리더십으로, 자신의 조직을 고성과조직으로 이끄는 성과관리리더십 스킬을 함양하는 교육입니다.",
      src: "/training/leadership/performance",
      name: 'performance',
      title: "교육 목표",
      desc: "- 퍼포먼스리더십의 개념을 이해하고, 고성과 조직으로의 팀을 설계하는 방법을 습득한다.\n - 조직원들의 성과관리 매니지먼트 능력을 함양한다.",
      title2: "교육 개요",
      desc2: "- 대상 : 매니저, 임원 \n - 시간 : 4시간~16시간 \n - 인원 : 20명 내외",
      image: "/trperformance.png",
      image2: "/trperformance2.png",
    },
    {
      id: 2,
      subject: "코칭 리더십",
      summ: "코칭을 통해 조직원들을 존중과 격려 소통을 통해 조직원들의 성장과 동기부여를 통해 자발적으로 목표를 달성하도록 이끄는 리더십을 향상시키는 교육입니다.",
      src: "/training/leadership/coaching",
      name: 'coaching',
      title: "교육 목표",
      desc: "- 코칭리더십의 개념을 이해 하고, 고성과 조직으로의 팀을 설계하는 방법을 습득한다.\n - 조직원들의 성과관리 매니지먼트 능력을  함양한다.",
      title2: "교육 개요",
      desc2: "- 대상 : 매니저, 임원 \n - 시간 : 4시간~16시간 \n - 인원 : 20명 내외",
      image: "/trcoaching.png",
      title3: "세부 내용",
      image2: "/trcoaching2.png",
    },
    {
      id: 3,
      subject: "팀장 리더십",
      summ: "조직내 팀장의 역할인식을 통해 팀장의 역량을 향상시킴으로써 팀목표달성과 팀성과를 향상시키는 교육입니다.",
      src: "/training/leadership/team",
      name: 'team',
      title: "교육 목표",
      desc: "- 조직내 팀장의 역할 및 팀장의 역할을 성공적으로 수행하는데 필요한 역량이 무엇인지를 이해한다.\n - 팀장에게 필요한 역량들을 학습하고 스킬을 향상시킨다.",
      title2: "교육 개요",
      desc2: "- 대상 : 팀장 \n - 시간 : 4시간~16시간 \n - 인원 : 20명 내외",
      image: "/trteam.png",
      title3: "세부 내용",
      image2: "/trteam2.png",
    },
  ],
  sales: [
    {
      id: 1,
      subject: "퍼포먼스 세일즈",
      summ: "고객 중심의 세일즈 마인드셋을 기초로 고객과 장기적인 파트너십을 맺고 성과를 창출 할 수 있는 세일즈 프로세스와 스킬을 향상시키는 교육입니다.",
      src: "/training/sales/performance",
      name: 'performance',
      title: "교육 목표",
      desc: "- 고객 중심적 마인드셋을 기반으로 하는 영업전문가의 핵심가치, 프로세스, 스킬을  이해한다. \n - 고객과 상호 신뢰적이고 장기적인 파트너십을 만들고 확장할 수 있는 세일즈 전략과 스킬을 습득한다.  \n - 고객의 목표달성을 지원하는 솔루션으로써 제품과 서비스의 가치와 이익을 디자인하고 전달한다.",
      title2: "교육 개요",
      desc2: "- 대상 : 영업직무 담당자 \n - 시간 : 4시간~16시간\n - 인원 : 20명 내외",
      image: "/trsperformance.png",
      image2: "/trsperformance2.png",
    },
    {
      id: 2,
      subject: "프레젠테이션 실전",
      summ: "프레젠터의 강점을 활용하여 자사의 제품( 또는 서비스)을 논리적으로 소개하고 고객을 설득하여 필요를 도출하는 교육입니다.",
      src: "/training/sales/presentation",
      name: 'presentation',
      title: "교육 목표",
      desc: "- 프레젠테이션 에센스를 파악한다.\n - 긍정적이고 설득력 있는 PR을 습득한다. \n - 스토리텔링기법을 활용하여 청중과 친밀한 관계를 형성한다. \n - 자사의 제품(서비스)을 논리적으로 PR하여 고객의 필요을 도출한다.",
      title2: "교육 개요",
      desc2: "- 대상 : 매니저, 기획담당자, 세일즈 담당자 \n - 시간 : 6~8시간 \n - 인원 : 10명 내외",
      image: "/trpresentation.png",
      image2: "/trpresentation2.png",

    },
    {
      id: 3,
      subject: "고성과 팀빌딩(1)",
      summ: "상호 보완적 기능을 가진 소수의 사람이 공유된 목표와 목적 아래 자신의 역할과 책임을 보다 헌신적으로 수행하여 고성과를 만들 수 있는 팀을 운영할 수 있는 교육입니다.",
      src: "/training/sales/building1",
      name: 'building1',
      title: "교육 목표",
      desc: "- 고성과 팀을 위한 전략적 마인드 구축, 최고의 팀을 위한 팀워크 구축 및 조직의 흐름을 이해한다\n - 창의적 마인드 함양을 통한 조직의 경영환경 이해하고 목표 및 실행의 중요성을 극대화 시킨다",
      title2: "교육 개요",
      desc2: "- 대상 : 중간 관리자 \n - 시간 : 4시간~8시간\n - 인원 : 20~30명 내외",
      image: "/trbuilding1.png",
      image2: "/trbuilding12.png",

    },
    {
      id: 4,
      subject: "고성과 팀빌딩(2)",
      summ: "상호 보완적 기능을 가진 소수의 사람이 공유된 목표와 목적 아래 자신의 역할과 책임을 보다 헌신적으로 수행하여 고성과를 만들 수 있는 팀을 운영할 수 있는 교육입니다.",
      src: "/training/sales/building2",
      name: 'building2',
      title: "프로그램 세부 내용",
      desc: "- 고성과 팀을 위한 전략적 마인드 구축, 최고의 팀을 위한 팀워크 구축 및 조직의 흐름을 이해한다\n - 창의적 마인드 함양을 통한 조직의 경영환경 이해하고 목표 및 실행의 중요성을 극대화 시킨다",
      title2: "교육 개요",
      desc2: "- 대상 : 중간 관리자 \n - 시간 : 4시간~8시간\n - 인원 : 20~30명 내외",
      image: "/trbuilding1.png",
      image2: "/trbuilding2.png",
    },
  ],
  interviewer: [
    {
      id: 1,
      subject: "면접관 교육",
      summ: "인사관리의 시작은 좋은 인재를 선발하는 것에서 시작합니다. 따라서 인재 선발에서 가장 중요한 과정인 면접을 효과적으로 진행하기 위해 체계적인 면접관 교육을 하는 과정입니다.",
      src: "/training/interviewer/interviewer",
      name: 'interviewer',
      title: "교육 목표",
      desc: "- 회사가 원하고 지원자가 생각하는 기본적 요건을 명확하게 판단하여 인재 적합도를 극대화한다. \n - 구조화된 질문을 통해 우리회사의 인재 적합도와 미래 행동을 예측할수 있다.",
      title2: "교육 개요",
      desc2: "- 대상 : 매니저, 임원 \n - 시간 : 4시간 \n - 인원 : 20명 내외",
      image: "/trinterviewer.png",
      image2: "/trinterviewer2.png",
    },
    {
      id: 2,
      subject: "일잘러 입문 과정",
      summ: "모든 직업인들에게 공통적으로 요구되는 기본적인 능력 및 자질을 갖출 수 있도록 구성된 교육과정입니다.",
      src: "/training/interviewer/basics",
      name: 'basics',
      title: "교육 목표",
      desc: "- 직업기초능력의 개발의 필요성을 이해하고, 주니어 직급에서 요구되는 능력을 배양할 수 있다. \n - 직업기초능력 향상을 통해 조직성과에 기여할 수 있다.",
      title2: "교육 개요",
      desc2: "- 신입사원~대리급 \n - 시간 : 4시간~20시간 \n - 인원 : 20명 내외",
      image: "/trbasics.png",
      title3: "세부 내용",
      image2: "/trbasics2.png",
    },
  ],
}
