export const items = {
  leadership: [
    {
      id: 1,
      name: 'performance',
      title: "교육 목표",
      desc: "- 퍼포먼스리더십의 개념을 이해하고, 고성과 조직으로의 팀을 설계하는 방법을 습득한다.\n - 조직원들의 성과관리 매니지먼트 능력을 함양한다.",
      title2: "교육 개요",
      desc2: "- 대상 : 매니저, 임원 \n - 시간 : 4시간~16시간 \n - 인원 : 20명 내외",
      image: "/trperformance.png",
    },
    {
      id: 2,
      name: 'coaching',
      title: "교육 목표",
      desc: "- 코칭리더십의 개념을 이해 하고, 고성과 조직으로의 팀을 설계하는 방법을 습득한다.\n - 조직원들의 성과관리 매니지먼트 능력을  함양한다.",
      title2: "교육 개요",
      desc2: "- 대상 : 매니저, 임원 \n - 시간 : 4시간~16시간 \n - 인원 : 20명 내외",
      image: "/trcoaching.png",
      title3: "세부 내용",
      image2: "/trcoaching2.png",
    },
    {
      id: 3,
      name: 'team',
      title: "교육 목표",
      desc: "- 조직내 팀장의 역할 및 팀장의 역할을 성공적으로 수행하는데 필요한 역량이 무엇인지를 이해한다.\n - 팀장에게 필요한 역량들을 학습하고 스킬을 향상시킨다.",
      title2: "교육 개요",
      desc2: "- 대상 : 팀장 \n - 시간 : 4시간~16시간 \n - 인원 : 20명 내외",
      image: "/trteam.png",
      title3: "세부 내용",
      image2: "/trteam2.png",
    },
  ],
  sales: [
    {
      id: 1,
      name: 'performa',
      title: "영업 목표",
      desc: "- 영업 전략의 이해 및 실행 방법 습득\n - 고객 관리 및 영업 실적 향상 방법 학습",
      title2: "교육 개요",
      desc2: "- 대상 : 영업 직원, 매니저\n - 시간 : 4시간~16시간\n - 인원 : 20명 내외",
      image: "/trsales.png",
    },
    {
      id: 2,
      name: 'presentation',
      title: "영업 목표",
      desc: "- 영업 전략의 이해 및 실행 방법 습득\n - 고객 관리 및 영업 실적 향상 방법 학습",
      title2: "교육 개요",
      desc2: "- 대상 : 영업 직원, 매니저\n - 시간 : 4시간~16시간\n - 인원 : 20명 내외",
      image: "/trsales.png",
    },
    {
      id: 3,
      name: 'building1',
      title: "영업 목표",
      desc: "- 영업 전략의 이해 및 실행 방법 습득\n - 고객 관리 및 영업 실적 향상 방법 학습",
      title2: "교육 개요",
      desc2: "- 대상 : 영업 직원, 매니저\n - 시간 : 4시간~16시간\n - 인원 : 20명 내외",
      image: "/trsales.png",
    },
    {
      id: 4,
      name: 'building2',
      title: "영업 목표",
      desc: "- 영업 전략의 이해 및 실행 방법 습득\n - 고객 관리 및 영업 실적 향상 방법 학습",
      title2: "교육 개요",
      desc2: "- 대상 : 영업 직원, 매니저\n - 시간 : 4시간~16시간\n - 인원 : 20명 내외",
      image: "/trsales.png",
    },
  ]

};
